services:
#    club.example:
#        class: ClubBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    annee.bissextile:
        class: ClubBundle\Service\AnneeBissextileService
        arguments: [2022]